### ISSUE TITLE
One problem

### ISSUE THREAD

**Issue by ttasb** [FBLADL/ACPL#9]
mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "D:\anaconda3\envs\ACPL2\lib\site-packages\torch\multiprocessing\spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "D:\anaconda3\envs\ACPL2\lib\site-packages\torch\multiprocessing\spawn.py", line 188, in start_processes
    while not context.join():
  File "D:\anaconda3\envs\ACPL2\lib\site-packages\torch\multiprocessing\spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "D:\anaconda3\envs\ACPL2\lib\site-packages\torch\multiprocessing\spawn.py", line 59, in _wrap
    fn(i, *args)
\ACPL-main1\main.py", line 44, in main_worker
    trainer.pipeline_master(args)
\ACPL-main1\pl_trainer.py", line 74, in pipeline_master
    lpul = PLUL(
  File "\ACPL-main1\pl_utils.py", line 21, in __init__
    self.local_info = self.build_local_graph(
  File "D:\ACPL代码\ACPL-main1\pl_utils.py", line 63, in build_local_graph
    D_ulf, I_ulf = gpu_index_ulf.search(u_embed, args.topk)
  File "D:\anaconda3\envs\ACPL2\lib\site-packages\faiss\__init__.py", line 286, in replacement_search
    n, d = x.shape
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by Lewisonez** [comment]
I came across the same problem
